[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
N8N_HOST = "0.0.0.0"
N8N_PORT = "5678"
N8N_PROTOCOL = "https"
N8N_BASIC_AUTH_ACTIVE = "true"
WEBHOOK_URL = "https://${{RAILWAY_STATIC_URL}}"
N8N_EDITOR_BASE_URL = "https://${{RAILWAY_STATIC_URL}}"

[experimental]
incrementalBuildCache = true
